### ISSUE TITLE
Cannot install from source

### ISSUE THREAD

**Issue by NikiforovAll** [FuseInfoTech/FitCLI#1]
Hi, 
Cannot link this plugin to sfdx engine.
Command: 
sfdx plugins:link
Error: 
Running prepare script for ~/FitCLI... !
 ▸    'MODULE_NOT_FOUND': Cannot find module 'salesforce-alm'
>lsb_release -a
Description:	Ubuntu 16.04.3 LTS
>npm --version 
5.3.0
>sfdx --version 
sfdx-cli/6.0.9-3391781 (linux-x64) node-v8.6.0

**Comment by FishOfPrey** [comment]
Hi,

The reference to salesforce-alm is from [forceUtils.js](https://github.com/FuseInfoTech/FitCLI/blob/f085018c8b3af22894bf94f54c3ee097e6830b38/lib/forceUtils.js), which it turn is based off the same class from Wade Wegnar's [forceUtil.js](https://github.com/wadewegner/sfdx-waw-plugin/blob/1e419721ead5229dbfd856e18a31e52bb47989ca/lib/forceUtils.js).

It's ultimately looking for the salesforce-alm/dist/lib/scratchOrgApi.js file. Is that in your file system?
